_settings_attrs_:
- cycles
- cycles_curves
- display
- display_settings
- grease_pencil_settings
- sequencer_colorspace_settings
- tool_settings
- unit_settings
- view_settings
cycles:
  adaptive_min_samples: 0
  adaptive_threshold: 0.009999999776482582
  ao_bounces: 1
  ao_bounces_render: 1
  auto_scrambling_distance: false
  bake_type: COMBINED
  blur_glossy: 1.0
  camera_cull_margin: 0.10000000149011612
  caustics_reflective: true
  caustics_refractive: true
  debug_bvh_layout: EMBREE
  debug_bvh_time_steps: 0
  debug_bvh_type: DYNAMIC_BVH
  debug_use_compact_bvh: false
  debug_use_cpu_avx: true
  debug_use_cpu_avx2: true
  debug_use_cpu_sse2: true
  debug_use_cpu_sse3: true
  debug_use_cpu_sse41: true
  debug_use_cuda_adaptive_compile: false
  debug_use_hair_bvh: true
  debug_use_optix_debug: false
  debug_use_spatial_splits: false
  denoiser: OPENIMAGEDENOISE
  denoising_input_passes: RGB_ALBEDO_NORMAL
  denoising_prefilter: ACCURATE
  device: CPU
  dicing_rate: 1.0
  diffuse_bounces: 4
  direct_light_sampling_type: MULTIPLE_IMPORTANCE_SAMPLING
  distance_cull_margin: 50.0
  fast_gi_method: REPLACE
  feature_set: SUPPORTED
  film_exposure: 1.0
  film_transparent_glass: false
  film_transparent_roughness: 0.10000000149011612
  filter_width: 1.5
  glossy_bounces: 4
  light_sampling_threshold: 0.009999999776482582
  max_bounces: 12
  max_subdivisions: 12
  min_light_bounces: 0
  min_transparent_bounces: 0
  motion_blur_position: CENTER
  name: ''
  offscreen_dicing_scale: 4.0
  pixel_filter_type: BLACKMAN_HARRIS
  preview_adaptive_min_samples: 0
  preview_adaptive_threshold: 0.10000000149011612
  preview_denoiser: AUTO
  preview_denoising_input_passes: RGB_ALBEDO
  preview_denoising_prefilter: FAST
  preview_denoising_start_sample: 1
  preview_dicing_rate: 8.0
  preview_pause: false
  preview_samples: 1024
  preview_scrambling_distance: false
  rolling_shutter_duration: 0.10000000149011612
  rolling_shutter_type: NONE
  sample_clamp_direct: 0.0
  sample_clamp_indirect: 10.0
  sample_offset: 0
  samples: 4096
  sampling_pattern: PROGRESSIVE_MULTI_JITTER
  scrambling_distance: 1.0
  seed: 0
  shading_system: false
  texture_limit: 'OFF'
  texture_limit_render: 'OFF'
  tile_size: 2048
  time_limit: 0.0
  transmission_bounces: 12
  transparent_max_bounces: 8
  use_adaptive_sampling: true
  use_animated_seed: false
  use_auto_tile: true
  use_camera_cull: false
  use_denoising: true
  use_distance_cull: false
  use_fast_gi: false
  use_layer_samples: USE
  use_preview_adaptive_sampling: true
  use_preview_denoising: false
  volume_bounces: 0
  volume_max_steps: 1024
  volume_preview_step_rate: 1.0
  volume_step_rate: 1.0
cycles_curves:
  name: ''
  shape: RIBBONS
  subdivisions: 2
display:
  matcap_ssao_attenuation: 1.0
  matcap_ssao_distance: 0.20000000298023224
  matcap_ssao_samples: 16
  render_aa: '8'
  shadow_focus: 0.0
  shadow_shift: 0.10000000149011612
  viewport_aa: FXAA
display_settings:
  display_device: sRGB
grease_pencil_settings:
  antialias_threshold: 1.0
sequencer_colorspace_settings:
  name: sRGB
tool_settings:
  annotation_stroke_placement_view2d: IMAGE
  annotation_stroke_placement_view3d: CURSOR
  annotation_thickness: 3
  auto_keying_mode: ADD_REPLACE_KEYS
  double_threshold: 0.0010000000474974513
  gpencil_selectmode_edit: POINT
  gpencil_stroke_placement_view3d: ORIGIN
  gpencil_stroke_snap_mode: NONE
  keyframe_type: KEYFRAME
  lock_markers: false
  lock_object_mode: true
  proportional_edit_falloff: SMOOTH
  proportional_size: 1.0
  show_uv_local_view: false
  snap_face_nearest_steps: 1
  snap_node_element: GRID
  snap_target: CLOSEST
  snap_uv_element: INCREMENT
  transform_pivot_point: MEDIAN_POINT
  use_auto_normalize: false
  use_edge_path_live_unwrap: false
  use_gpencil_automerge_strokes: false
  use_gpencil_draw_additive: false
  use_gpencil_draw_onback: false
  use_gpencil_select_mask_point: false
  use_gpencil_select_mask_segment: false
  use_gpencil_select_mask_stroke: false
  use_gpencil_stroke_endpoints: false
  use_gpencil_thumbnail_list: true
  use_gpencil_vertex_select_mask_point: false
  use_gpencil_vertex_select_mask_segment: false
  use_gpencil_vertex_select_mask_stroke: false
  use_gpencil_weight_data_add: false
  use_keyframe_cycle_aware: false
  use_keyframe_insert_auto: false
  use_keyframe_insert_keyingset: false
  use_lock_relative: false
  use_mesh_automerge: false
  use_mesh_automerge_and_split: false
  use_multipaint: false
  use_proportional_action: false
  use_proportional_connected: false
  use_proportional_edit: false
  use_proportional_edit_mask: false
  use_proportional_edit_objects: false
  use_proportional_fcurve: false
  use_proportional_projected: false
  use_record_with_nla: false
  use_snap: false
  use_snap_align_rotation: false
  use_snap_backface_culling: false
  use_snap_edit: true
  use_snap_grid_absolute: false
  use_snap_node: false
  use_snap_nonedit: true
  use_snap_peel_object: false
  use_snap_project: false
  use_snap_rotate: false
  use_snap_scale: false
  use_snap_selectable: false
  use_snap_self: true
  use_snap_sequencer: false
  use_snap_to_same_target: false
  use_snap_translate: true
  use_snap_uv: false
  use_snap_uv_grid_absolute: false
  use_transform_correct_face_attributes: false
  use_transform_correct_keep_connected: false
  use_transform_data_origin: false
  use_transform_pivot_point_align: false
  use_transform_skip_children: false
  use_uv_select_sync: false
  uv_relax_method: LAPLACIAN
  uv_sculpt_all_islands: false
  uv_sculpt_lock_borders: false
  uv_select_mode: VERTEX
  uv_sticky_select_mode: SHARED_LOCATION
  vertex_group_subset: ALL
  vertex_group_user: NONE
  vertex_group_weight: 1.0
  workspace_tool_type: FALLBACK
unit_settings:
  length_unit: METERS
  mass_unit: KILOGRAMS
  scale_length: 1.0
  system: METRIC
  system_rotation: DEGREES
  temperature_unit: KELVIN
  time_unit: SECONDS
  use_separate: false
view_settings:
  exposure: 0.0
  gamma: 1.0
  look: None
  use_curve_mapping: false
  view_transform: Filmic
